LABEL_CLASSES = {
    "No Data": 0,
    "Mines and Quarries": 1,
    "Urban Areas": 35,
    "Lakes and dams": 3,
    "Salt lakes": 4,
    "Irrigated cropping": 5,
    "Rain fed cropping": 8,
    "Irrigated pasture": 6,
    "Rain fed pasture": 9,
    "Irrigated sugar": 7,
    "Rain fed sugar": 10,
    "Wetlands": 11,
    "Alpine meadows": 15,
    "Open Hummock Grassland": 16,
    "Closed Tussock Grassland": 14,
    "Open Tussock Grassland": 18,
    "Scattered shrubs and grasses": 19,
    "Dense Shrubland": 24,
    "Open Shrubland": 25,
    "Closed Forest": 31,
    "Open Forest": 32,
    "Woodland": 34,
    "Open Woodland": 33
}
